version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/elastic-apm-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
          environment:
            COMPOSER_MEMORY_LIMIT: -1
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

  code_linter:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/elastic-apm-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
          environment:
            COMPOSER_MEMORY_LIMIT: -1
      - run:
          name: Lint PHP code
          command: php ./vendor/bin/php-cs-fixer fix --config .php_cs --dry-run --diff

  unit_tests:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/elastic-apm-laravel
    environment:
      CC_TEST_REPORTER_ID: 23639f09f4ef515ddb5fea9baf90f9f5cd9bb5e0801cf1dc062d993a3d70d3eb
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
          environment:
            COMPOSER_MEMORY_LIMIT: -1
      - run:
          name: Install Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run unit tests
          command: |
            ./cc-test-reporter before-build
            ./vendor/bin/codecept run --xml test_report.xml --coverage --coverage-html --coverage-xml
            mv tests/_output/coverage.xml clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - code_linter:
          requires:
            - build
      - unit_tests:
          requires:
            - build
