version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/elastic-apm-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: 
          name: Composer install
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

  code_linter:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/elastic-apm-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - run: php ./vendor/bin/php-cs-fixer fix src --rules=@PSR2,@Symfony,@PhpCsFixer --dry-run --diff

  unit_tests:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/elastic-apm-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: 
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run unit tests
          command: ./vendor/bin/codecept run unit --xml unit_test_report.xml --coverage
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - code_linter:
          requires:
            - build
      - unit_tests:
          requires:
            - build
